Feature/ui roles
ssds-team/Tenders pull request #526
Opened 2020-08-03 14:46 UTC by tatianaIljina

2020-10-14 17:52 UTC, DamienVStone requested changes
merge conflicts please

2020-10-15 15:00 UTC, tatianaIljina commented on API/Tenders.API/Controllers/DistributionGroupController.cs
> +            return this.BadRequest("�� ������� �������� ������ ��������, ����������� ������.");
!!!

2020-10-16 08:59 UTC, tatianaIljina commented on API/Tenders.API/Controllers/DistributionGroupSmrController.cs
> +            var res = data.Select(r => new DistribuitonGroupViewModel
select in new method Map()

2020-10-16 09:00 UTC, tatianaIljina commented on API/Tenders.API/Controllers/DistributionGroupSmrController.cs
> +                return this.NoContent();
return BadRequest()

2020-10-16 09:00 UTC, tatianaIljina commented on API/Tenders.API/Controllers/DistributionGroupSmrController.cs
> +            mapInstance.DistributionType = value.DistributionType;
Map()

2020-10-16 09:01 UTC, tatianaIljina commented on Sberbank/Tenders.Sberbank.Requesting/Program.cs
> +namespace Tenders.Sberbank.Requesting
check

2021-03-26 05:59 UTC, closed without merging