Feature/addressees2
ssds-team/Tenders pull request #613
Opened 2020-09-30 09:00 UTC by tatianaIljina

2020-10-08 14:31 UTC, Anny777 requested changes

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Controllers/DistributionGroupController.cs
> +                return this.NoContent();
return bad request

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Controllers/DistributionGroupController.cs
> +                return this.Created(new Uri($"/api/DistributionGroup?id={res.Id}", UriKind.Relative), new { res });
Retutrn created at action: 
Example:
var idCreatedObj = new { id = IdObj};
return this.CreatedAtAction(nameof(this.Get), idCreatedFile, idCreatedFile);

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Controllers/DistributionGroupController.cs
> +            return this.StatusCode(500, $"�������������� ������. �� ������� �������� ��������.");
Check the encoding file. Should be UTF-8

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Controllers/DistributionGroupController.cs
> +                return this.NoContent();
return bad request

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Controllers/DistributionGroupController.cs
> +            var res = data.Select(r => this.ConvertToViewModel(r)).ToArray();
what happens if this.ConvertToViewModel(r) returned null?

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Controllers/DistributionRegionController.cs
> +            var entity = this.regionRepository.Find(id.ToString());
Why Find have input parameter string? Why not guid?

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Controllers/DistributionRegionController.cs
> +                return this.NoContent();
return bad request

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Controllers/DistributionRegionController.cs
> +                return this.Created(new Uri($"/api/DistributionRegion?id={res.Id}", UriKind.Relative), new { res });
Return created at action

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Controllers/DistributionRegionController.cs
> +                return this.NoContent();
return bad request

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Migrations/20200911064302_Initial-Create.cs
> +                    Id = table.Column<string>(nullable: false),
Id must be Guid!

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Migrations/20200911064302_Initial-Create.cs
> +                    Id = table.Column<string>(nullable: false),
Guid

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Models/DistributionGroup.cs
> +        [QuickSearch]
Quick search delete

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Models/DistributionGroup.cs
> +    public class DistributionGroup : ModelBase, IDistributionGroup
Model base delete

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Models/DistributionGroupViewModel.cs
> +        public string Id { get; set; }
Guid

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Models/DistributionGroupViewModel.cs
> +        public string DistributionRegionId { get; set; }
Guid

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Models/DistributionRegion.cs
> +        [QuickSearch]
Delete all quick search attributes

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Models/FilterOptions.cs
> +    {
Delete this object,  search will be via devextreme.

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/ServiceRegistrationPoint.cs
> +            RegisterModelBaseFactory<IDistributionGroup, DistributionGroup>(sc);
Delete all used model base factory.

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Abstraction/IRepository.cs
> +    public interface IRepository<out TEntity>
For what abstract repository? 
Is it possible to describe these methods in needing repositories?

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Abstraction/IDistributionGroupRepository.cs
> +        bool Delete(string id);
Id must be guid

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Services/DistributionGroupRepository.cs
> +            var newInstance = this.distributionGroupFactory.MakeInstance();
May be via new? And used factory deleted

2020-10-08 14:31 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.API/Services/DistributionGroupRepository.cs
> +            this.quickSearchService.GenerateQuickSearchString(newInstance);
delete generate quick search

2020-10-14 18:22 UTC, Anny777 requested changes

2020-10-14 18:22 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.Client/DistributionGroupClient.cs
> +            var response = await Policy.Handle<HttpRequestException>()
Added using on response

2020-10-14 18:22 UTC, Anny777 commented on Services/Utilities/Addressees/Addressees.Client/DistributionRegionClient.cs
> +            var response = await Policy.Handle<HttpRequestException>()
Added using on response

2020-10-15 09:09 UTC, tatianaIljina commented on UI/src/app/modules/settings/components/distribution/services/distribution.service.ts
> +    return this.http.get<KeyValuePair<number, string>[]>(this.controllerUrl + 'GetDistributionEnum');
GetEnum

2020-10-20 08:46 UTC, Anny777 approved these changes

2020-10-20 08:54 UTC, merged