Feature/cust handler
ssds-team/Tenders pull request #637
Opened 2020-10-13 13:26 UTC by tatianaIljina

2020-10-14 07:35 UTC, DamienVStone requested changes

2020-10-14 07:35 UTC, DamienVStone commented on BuildingBlocks/EventBus/MessageBroker/Extensions/CustomersTopic/CustomersRegistrationHelper.cs
> +            const string topic = "queue.customer";
!

2020-10-14 07:35 UTC, DamienVStone commented on Services/Customers/Customers.Handler/Services/CustomerHandler.cs
> +                this.logger.LogError(ex, "An error has occurred");
rethrow exception

2020-10-14 17:47 UTC, DamienVStone requested changes
there is no docker file

2020-10-30 08:11 UTC, Anny777 approved these changes

2020-10-30 08:21 UTC, DamienVStone approved these changes

2020-10-30 08:21 UTC, merged