Feature/ftp entry api
ssds-team/Tenders pull request #665
Opened 2020-10-29 14:10 UTC by tatianaIljina

2020-11-12 12:48 UTC, Anny777 requested changes

2020-11-16 10:51 UTC, tatianaIljina commented on Services/FtpEntries/FtpEntries.FtpPathHandler/Services/Ftp223Producer.cs
> +    public class Ftp223Producer : FtpProducer, IFtp223Producer
FtpProducer uses path info and ftp entry models in SendFiles().
If we moved FtpProducer to API from Handler, we need to transfer PathInfo model with FtpEntry (now we transfer only path id)
So, API can't parse to models with from body attribute. We need smth like this:
https://stackoverflow.com/questions/14407458/webapi-multiple-put-post-parameters
but i think it is a bad solution. Have you got any idea?

2020-11-20 08:22 UTC, Anny777 requested changes

2020-12-03 15:30 UTC, DamienVStone requested changes

2020-12-03 15:30 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Models/DataSourceLoadOptions.cs
> +#pragma warning disable SA1402 // File may only contain a single type
Split file.

2020-12-03 15:30 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpPathController.cs
> +            var paths = this.ftpPathRepository.Get();
It's bad idea to expose IQueryable<T> from repository. In this rarly case you can hide using of DataSourceLoader in to repository. But make especial method like GetLoadResultAsync(...). You need to make methods in controller async as well

2020-12-03 15:30 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpPathController.cs
> +            loadOptions.PrimaryKey = new[] { "Id" };
Can you hide it in DataSourceLoadOptions ctor?

2020-12-03 15:30 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpPathController.cs
> +            if (pathId == Guid.Empty)
Path not found in this case

2020-12-03 15:30 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpPathController.cs
> +            if (this.ftpPathRepository.Exist(path.Path))
Let's talk about it on daily meeting

2020-12-16 15:11 UTC, DamienVStone requested changes

2020-12-16 15:11 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpPathController.cs
> +            var path = this.ftpPathRepository.Get(pathId);
Make it Async

2020-12-16 15:11 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Models/FtpPath.cs
> +        public string Path { get; set; }
Make it Uri

2020-12-16 15:11 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpPathController.cs
> +                    return this.CreatedAtAction(nameof(this.Get), result, result);
It will cause of invalid location header

2020-12-16 15:11 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpPathController.cs
> +            if (!this.ftpPathRepository.Delete(id))
Make it async

2020-12-16 15:11 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpPathController.cs
> +            var oldPath = this.ftpPathRepository.Get(path.Id);
Make it async

2020-12-16 15:11 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpEntryController.cs
> +        public async Task<ActionResult> Post([FromBody]FtpEntryDto dto, Guid pathId)
Maybe it's make sense to move pathId to dto?

2020-12-16 15:11 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpEntryController.cs
> +                    return this.CreatedAtAction(nameof(this.Post), res, res);
Use just Created and try to pass identifiers of created entries in response body

2020-12-16 15:11 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpEntryController.cs
> +                return this.Conflict(ex);
Do not pass exception to server response!

2020-12-16 15:11 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpEntryController.cs
> +            var res = await this.ftpManager.SetProcessed(entryId).ConfigureAwait(false);
What if entry doesn't exists?

2020-12-16 15:11 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Services/FtpEntryManager.cs
> +        public async Task<IFtpEntry[]> TryWriteEntry(IFtpEntry[] entriesToSave, Guid operationId, Guid pathId)
Rename to "SaveAsync"

2020-12-16 15:11 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Models/FtpEntryDto.cs
> +        private readonly FtpEntry[] m_ftpEntries;
Why dto looks like EF aggreagte model? It's unnecessary

2020-12-17 07:23 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpSyncController.cs
> +                var paths = this.ftpPathRepository.Get().Select(c => this.MapToPathInfo(c, Guid.NewGuid())).AsQueryable(); // use process id
1. Use Guid.Empty
2. Why you use AsQueryable() and then .ToArray()?

2020-12-17 08:12 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpSyncController.cs
> +                this.logger.LogCritical(e, e.Message);
Don't swallow Exception, rethrow it

2020-12-17 08:14 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Dockerfile
> +ENTRYPOINT ["dotnet", "FtpEntries.API.dll"]
check other api docker files

2020-12-17 08:14 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/FtpEntries.API.csproj
> +  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
clean up file as in agregatoreat.requesting.csproj

2020-12-17 08:20 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Migrations/20201206181102_Initial-Create.cs
> +                    Path = table.Column<string>(type: "text", nullable: false),
create unique index

2020-12-17 08:22 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Migrations/20201206181102_Initial-Create.cs
> +                    PathId = table.Column<Guid>(type: "uuid", nullable: true),
try to create unique index

2020-12-31 08:41 UTC, DamienVStone approved these changes

2020-12-31 08:41 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Abstraction/IFtp44Producer.cs
> +        Task SendFiles(IFtpEntry[] entries, Guid operationId);
Pass FederalLaw via parameters and make one service for topic routing

2020-12-31 08:41 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Abstraction/IFtpPathRepository.cs
> +        IEnumerable<FtpPath> Get();
Make methods async

2020-12-31 08:41 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpEntryController.cs
> +            if (dto.FtpEntries == null || dto.FtpEntries.Count == 0)
Do not unite different errors in one response

2020-12-31 08:41 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Controllers/FtpEntryController.cs
> +                return this.BadRequest("Path id is empty.");
Maybe you mean Operation id?

2021-01-11 14:07 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Abstraction/IFtpEntryManager.cs
> +        Task<bool> SetProcessed(Guid entryId);
Async

2021-01-11 14:13 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Models/FtpEntryDto.cs
> +        public Guid OperationId => this.operationId;
Use just properties.

2021-01-11 14:15 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Models/LoadOptions/DataSourceLoadOptions.cs
> +            this.PrimaryKey = new[] { "Id" };
For what?

2021-01-11 14:15 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Models/LoadOptions/DataSourceLoadOptionsBinder.cs
> +    public class DataSourceLoadOptionsBinder : IModelBinder
For what?

2021-01-11 14:16 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Program.cs
> +            .ConfigureWebHostDefaults(webBuilder =>
Add APM

2021-01-11 14:26 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Services/Ftp223Producer.cs
> +            ValidateEntry(entry);
Use automapper

2021-01-11 14:26 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Services/Ftp44Producer.cs
> +            ValidateEntry(entry);
Use automapper

2021-01-11 14:28 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Migrations/20201206181102_Initial-Create.cs
> +                    PathId = table.Column<Guid>(type: "uuid", nullable: true),
It's required fields

2021-01-29 08:21 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.Client/Models/FtpEntry.cs
> +        public bool IsActive { get; set; }
Is it used?

2021-01-29 09:37 UTC, DamienVStone requested changes

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Services/FtpEntryManager.cs
> +            if (federalLaw == FederalLawType.Fl223)
Use switch/case with exception throwing

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Services/FtpEntryRepository.cs
> +            if (res != 1)
res < 1

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Services/FtpEntryRepository.cs
> +                var error = new UniqueIndexViolationException($"Error while setting processed state for entry: {entryId}");
Are you sure? It looks like MongoDb logic. Are you tested it case?

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Services/FtpEntryRepository.cs
> +                var res = this.db.SaveChanges();
async

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Services/FtpEntryRepository.cs
> +            var res = this.db.SaveChanges();
async

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.API/Services/FtpEntryRepository.cs
> +            var deletedCount = this.db.SaveChanges();
async

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.Client/FtpEntries.Client.csproj
> +  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
Clean up csproj files

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.Client/Abstraction/IFtpEntryClient.cs
> +        Task<IFtpEntry[]> Post(IFtpEntry[] values, Guid operationId, Guid path);
Rename it for more clearly understanding

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.Client/Abstraction/IFtpEntryClient.cs
> +        Task SetProcessed(string entryId);
It should be string?

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.FtpPathHandler/Core/Abstraction/Models/IFtpEntry.cs
> +        bool IsArchive { get; set; }
Is it used?

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.FtpPathHandler/Core/Abstraction/Models/IFtpEntry.cs
> +        DateTimeOffset Modified { get; set; }
Change to DateTime

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.FtpPathHandler/Core/Abstraction/Models/IFtpEntry.cs
> +        bool IsDirectory { get; set; }
Is it used?

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.FtpPathHandler/Core/Models/FtpEntryViewModel.cs
> +        public DateTimeOffset Modified { get; set; }
Change to DateTime

2021-01-29 09:37 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.FtpPathHandler/Models/FtpEntriesOptions.cs
> +        public string FtpPathTopic { get; set; }
it's unnecessary. Can you review your services and remove unused things?

2021-02-01 15:31 UTC, DamienVStone requested changes

2021-02-01 15:31 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.FtpPathHandler/FtpEntries.FtpPathHandler.csproj
> +  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
Clean up

2021-02-01 15:31 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.FtpPathHandler/Program.cs
> +            context.Configuration["ElasticApm:ServiceName"] = GetSender().Replace('.', '_');
It's unnecessary

2021-02-01 15:31 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.FtpPathHandler/Program.cs
> +                    .UseElasticApm(GetSubscribers())
Remove APM

2021-02-01 15:31 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.FtpPathHandler/Services/Handler.cs
> +            this.ftpEntryService.Handle(message, ct).ConfigureAwait(false);
wait it

2021-02-01 15:31 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.UnitTests/FtpEntries.UnitTests.csproj
> +  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
Clean up

2021-02-08 09:27 UTC, tatianaIljina reviewed
,.

2021-02-16 15:04 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.FtpPathHandler/Services/UbuntuFtpEntryParser.cs
> -            var changeDate = new DateTimeOffset(DateTime.Parse($"{parts[1]} {parts[2]} {year}", CultureInfo.GetCultureInfo("en-Us")), TimeSpan.FromHours(3));
You removed time zone, DateTime should be parsed as UTC+0300 and saved with UTC+0000 to storage

2021-02-16 15:07 UTC, DamienVStone commented on Services/FtpEntries/FtpEntries.FtpPathHandler/Services/FtpDirectoryReader.cs
> -            r.Modified = parsed.Modified.DateTime;
Make sure that dates saved to storage with zero time zone

2021-02-16 15:09 UTC, DamienVStone requested changes
end close

2021-02-26 07:08 UTC, DamienVStone approved these changes

2021-02-26 07:27 UTC, Anny777 approved these changes

2021-02-26 07:27 UTC, merged