Feature/eiszhs
ssds-team/Tenders pull request #745
Opened 2021-01-21 07:12 UTC by tatianaIljina

2021-01-25 09:24 UTC, DamienVStone requested changes

2021-01-25 09:39 UTC, DamienVStone requested changes

2021-01-25 09:39 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Services/EiszhsMonitoringHostedService.cs
> +                await Task.Run(
OMG what is it?

2021-01-26 10:33 UTC, tatianaIljina commented on BuildingBlocks/Infrastructure/Infrastructure.PdfReader/PdfReaderService.cs
> +                    PdfCanvasProcessor parser = new PdfCanvasProcessor(strategy);
I had the same mistake when created object out of the loop, SimpleTextExtractionStrategy saved the previous pages it has read
https://stackoverflow.com/questions/3704518/problem-with-pdftextextractor-in-itext

2021-01-26 12:14 UTC, tatianaIljina commented on BuildingBlocks/Infrastructure/Infrastructure.PdfReader/PdfReaderService.cs
> +                pdfReader.Close();
You are right. From itext repo:
void System.IDisposable.Dispose() {
            Close();
}

2021-01-26 12:54 UTC, DamienVStone approved these changes

2021-01-26 12:55 UTC, merged