Feature/logging
ssds-team/Tenders pull request #787
Opened 2021-02-16 07:33 UTC by tatianaIljina

2021-02-16 15:29 UTC, DamienVStone requested changes

2021-02-16 15:29 UTC, DamienVStone commented on RTS/Tenders.RTS.Bidding/Program.cs
> +            sc.AddNlogLogging(context.Configuration);
look at line 55

2021-02-16 15:29 UTC, DamienVStone commented on RTS/Tenders.RTS.Bidding/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
move it to .csproj file

2021-02-16 15:29 UTC, DamienVStone commented on RTS/Tenders.RTS.Bidding/Services/CometClient.cs
> +                this.logger.LogError(ex.Message);
use (Exception, string) overload

2021-02-16 15:29 UTC, DamienVStone commented on RTS/Tenders.RTS.Bidding/Services/CometClient.cs
> +                this.logger.LogError(ex.Message);
and here

2021-02-16 15:29 UTC, DamienVStone commented on Services/Addressees/Addressees.API/Models/UniqueIndexViolationException.cs
> +    public class UniqueIndexViolationException : Exception
Is it logging part too?

2021-02-16 15:29 UTC, DamienVStone commented on tests/Tenders.Core.Tests/Tenders.Core.Tests.csproj
> +    <ProjectReference Include="..\..\Core\Tenders.Core.NLogLoggerService\Tenders.Core.NLogLoggerService.csproj" />
Is it need?

2021-02-17 06:55 UTC, tatianaIljina commented on tests/Tenders.Core.Tests/Tenders.Core.Tests.csproj
> +    <ProjectReference Include="..\..\Core\Tenders.Core.NLogLoggerService\Tenders.Core.NLogLoggerService.csproj" />
yes, for LoggerServiceTest class

2021-02-17 06:55 UTC, tatianaIljina commented on Services/Addressees/Addressees.API/Models/UniqueIndexViolationException.cs
> +    public class UniqueIndexViolationException : Exception
no, of course. However, I saw unnecessary reference and decided to fix it as a part of this small pr :)

2021-02-20 09:29 UTC, Anny777 approved these changes

2021-02-20 09:34 UTC, DamienVStone approved these changes

2021-02-20 09:35 UTC, merged