Feature/addressees UI
ssds-team/Tenders pull request #793
Opened 2021-02-17 12:55 UTC by tatianaIljina

2021-03-01 14:59 UTC, Anny777 requested changes

2021-03-01 14:59 UTC, Anny777 commented on Services/Addressees/Addressees.API/Controllers/DistributionGroupController.cs
> +        public ActionResult Patch([FromForm]DistributionGroupViewModel item)
name method Patch but attribute HttpPut

2021-03-01 14:59 UTC, Anny777 commented on Services/Addressees/Addressees.API/Controllers/DistributionRegionController.cs
> +        public ActionResult Patch([FromForm]DistributionRegion region)
Name Path attribute Put

2021-03-01 14:59 UTC, Anny777 commented on UI/src/app/modules/settings/components/distribution-region/distribution-region.component.spec.ts
> +      await new Promise<void>(resolve => setTimeout(() => resolve(), 0));
Why set timeout?

2021-03-01 14:59 UTC, Anny777 commented on UI/src/app/modules/settings/components/distribution-region/distribution-region.component.ts
> +  private url = `${environment.host}${environment.auctionApplication}DistributionRegion/`;
Why environment.auctionApplication?

2021-03-02 07:31 UTC, tatianaIljina commented on UI/src/app/modules/settings/components/distribution-region/distribution-region.component.spec.ts
> +      await new Promise<void>(resolve => setTimeout(() => resolve(), 0));
to simulate time in test, because data loads not in at once

2021-03-03 12:43 UTC, Anny777 approved these changes

2021-03-03 13:06 UTC, Anny777 approved these changes

2021-03-03 13:06 UTC, merged