Feature/conf pipe
ssds-team/Tenders pull request #796
Opened 2021-02-19 13:33 UTC by tatianaIljina

2021-02-20 06:52 UTC, Anny777 requested changes

2021-02-20 06:52 UTC, Anny777 commented on API/Tenders.API.DAL.Postgres/ApiOptions.cs
> +        private readonly string addresseesByDivisonTemplate = string.Empty;
Convert to properties.

2021-02-20 06:52 UTC, Anny777 commented on API/Tenders.API/Services/ApiLocalConfigurationProvider.cs
> +    public class ApiLocalConfigurationProvider : ConfigurationProvider
Rename on EntityConfigurationProvider  or DbConfigurationProvider

2021-02-20 06:52 UTC, Anny777 commented on API/Tenders.API.DAL.Postgres/ApiOptions.cs
> +    public class ApiOptions
Don`t rename class.

2021-02-20 06:52 UTC, Anny777 commented on API/Tenders.API/Services/ApiOptions.cs
> +    public class ApiOptions
Why this class same Tenders.API.DAL?

2021-02-26 07:19 UTC, DamienVStone commented on API/Tenders.API.DAL.Postgres/Services/PostgresConfigService.cs
>      internal class PostgresConfigService : IPostgresConfigService
is it using anywhere?

2021-03-01 07:49 UTC, closed without merging