Feature/eiszhs to excel
ssds-team/Tenders pull request #801
Opened 2021-02-24 14:04 UTC by kpatrashanu

2021-02-25 08:49 UTC, Anny777 requested changes

2021-02-25 08:49 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.Reporter/Program.cs
> +            sc.AddHostedService<EiszhsReporterHostedService>();
Add Addresses client and eiszhs client registration

2021-02-25 08:49 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.Reporter/Services/EiszhsReporterHostedService.cs
> +        private readonly ExcelService excelService;
Why not interface?

2021-02-25 08:49 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.Client/IInfoEiszhsClient.cs
> +        Task<IEnumerable<InfoResidentialConstruction>> GetListInfoForPeriod(CancellationToken ct);
Maybe GetReport?

2021-02-25 08:49 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.Client/InfoEiszhsClient.cs
> +                }).ExecuteAsync(() => client.GetAsync(uri)).ConfigureAwait(false);
Pass the cancellation token

2021-02-25 08:49 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.Reporter/Services/ExcelService.cs
> +#if debug
Maybe without if debug. Leave on permanent.

2021-02-26 10:54 UTC, DamienVStone requested changes

2021-03-01 08:26 UTC, DamienVStone approved these changes

2021-03-01 08:26 UTC, Anny777 approved these changes

2021-03-01 08:27 UTC, merged