attachments added to mail handler
ssds-team/Tenders pull request #816
Opened 2021-03-11 13:44 UTC by kpatrashanu

2021-03-12 07:13 UTC, Anny777 requested changes

2021-03-12 07:13 UTC, Anny777 commented on Services/Mail/Mail.Handler/MailHostedService.cs
> +                    var attachments = this.PrepareAttachments(mail.AttachmentIds, cancellationToken);
await this.PrepareAttachments instead attachments.Result.

2021-03-12 07:13 UTC, Anny777 commented on Services/Mail/Mail.Handler/MailHostedService.cs
> +            if (attachmentIds == null || attachmentIds.Length == 0)
Best attachmentIds.Any() instead attachmentIds.Length == 0

2021-03-12 07:13 UTC, Anny777 commented on Services/Mail/Mail.Handler/MailHostedService.cs
> +            List<FileEntityDto> documents = new List<FileEntityDto>();
Just var instead List<FileEntityDto>

2021-03-12 07:13 UTC, Anny777 commented on Services/Mail/Mail.Handler/MailHostedService.cs
> +                    MailEntityDto mailDto = new MailEntityDto()
Just var.
 Refactor on any methods.

2021-03-12 08:28 UTC, kpatrashanu commented on BuildingBlocks/EventBus/MessageBroker/Extensions/MailTopic/MailInfo.cs
> +#pragma warning disable
Disable // Properties should not return arrays

2021-03-15 14:47 UTC, DamienVStone requested changes
You should write tests for test cases with attachments

2021-03-15 14:47 UTC, DamienVStone commented on Services/Mail/Mail.API/Services/MailEntityRepository.cs
> +                if (attachment.Name != null && attachment.Data.Any())
- Use string.IsNullOrWhitespace(...) instead of null check
- Check attachment's Data against null

2021-03-15 14:47 UTC, DamienVStone commented on Services/Mail/Mail.Handler/MailHostedService.cs
> +                    this.mailClient.Put(cancellationToken, mailDto).Wait();
Extract method and remove async, use Wait() instead

2021-03-19 07:01 UTC, Anny777 approved these changes

2021-03-19 07:03 UTC, DamienVStone approved these changes

2021-03-19 07:09 UTC, merged