Feature/config client
ssds-team/Tenders pull request #820
Opened 2021-03-16 17:28 UTC by tatianaIljina

Create following environment variables: 
       "ConfigOptions:GetConfigTemplate": "",
        "APIAUTHENTICATIONOPTIONS:Token": "",
        "APIAUTHENTICATIONOPTIONS:Credential:Password": "",
        "APIAUTHENTICATIONOPTIONS:Credential:UserName": "",
        "ProxyOptions:Address": "",
        "ProxyOptions:Credentials:UserName": "",
        "ProxyOptions:Credentials:Password": "",
        "ProxyOptions:Credentials:Domain": ""

2021-03-22 09:28 UTC, DamienVStone requested changes

2021-03-22 09:28 UTC, DamienVStone commented on Services/Configs/Configs.Client/ApiAuthenticationService.cs
> +            this.authOptions = new ApiAuthenticationOptions();
https://www.smarly.net/dependency-injection-in-net/di-catalog/di-anti-patterns/control-freak

2021-03-22 09:28 UTC, DamienVStone commented on Services/Configs/Configs.Client/ConfigsClient.cs
> +            this.configOptions = new ConfigOptions();
https://www.smarly.net/dependency-injection-in-net/di-catalog/di-anti-patterns/control-freak

2021-03-22 09:28 UTC, DamienVStone commented on Services/Configs/Configs.Client/Extensions/ServiceCollectionHelper.cs
> +#endif
Merge two #if blocks to one

2021-03-22 09:28 UTC, DamienVStone commented on Services/Configs/Configs.Client/Models/Options/ApiAuthenticationOptions.cs
> +            this.Token = new Uri(Environment.GetEnvironmentVariable("APIAUTHENTICATIONOPTIONS:Token"));
fill options in your instance of DI container

2021-03-24 08:27 UTC, DamienVStone commented on Services/Configs/Configs.Client/Models/Options/ConfigOptions.cs
> +        public Uri GetGetConfigUri(int skip = 0, int take = 0)
GetGetConfigUri -> MakeGetConfigUri

2021-03-24 08:28 UTC, DamienVStone commented on Services/Configs/Configs.Client/Models/Options/ConfigOptions.cs
> +            return new Uri(this.GetConfigByIdTemplate + id.ToString());
Use {{ID}} template phrase

2021-03-26 09:52 UTC, DamienVStone commented on BuildingBlocks/Infrastructure/Infrastructure.Configuration/Extensions/ConfigurationHelper.cs
> +            var serviceCollection = new ServiceCollection();
Since you have ServiceColleciton, you can change pure DI to using DI container.

2021-03-26 09:54 UTC, DamienVStone commented on Services/Configs/Configs.Client/ApiAuthenticationService.cs
> +            using var content = new StringContent(JsonSerializer.Serialize(credentials), Encoding.UTF8, MediaTypeNames.Application.Json);
Can you use helper for StringContent creation?

2021-03-26 09:55 UTC, DamienVStone commented on Services/Configs/Configs.Client/ConfigsClient.cs
> +            this.options = options.Value ?? throw new ArgumentNullException(nameof(options));
Strange validation, use options?.Value

2021-03-26 09:56 UTC, DamienVStone commented on Services/Configs/Configs.Client/Extensions/ServiceCollectionHelper.cs
> +#pragma warning disable
For what?

2021-03-26 12:27 UTC, tatianaIljina commented on Services/Configs/Configs.Client/Extensions/ServiceCollectionHelper.cs
> +#pragma warning disable
in prod mode we don't use some namespaces and build fails

2021-03-26 13:06 UTC, DamienVStone commented on Services/Configs/Configs.Client/Extensions/ServiceCollectionHelper.cs
> +#pragma warning disable
Do not use using statement, use explicit namespace path for a class like System.Net.NetworkCredential(...)

2021-04-01 08:39 UTC, DamienVStone approved these changes

2021-04-01 14:22 UTC, DamienVStone approved these changes

2021-04-01 14:23 UTC, merged