added auction ui link replace, sdt filter
ssds-team/Tenders pull request #829
Opened 2021-03-19 12:05 UTC by kpatrashanu

2021-03-19 13:39 UTC, tatianaIljina commented on Services/AuctionApplication/AuctionApplication.API/Abstraction/Models/Enums/ShortSupplierDeterminationType.cs
> +    public enum ShortSupplierDeterminationType
Is it possible to avoid duplication of supplier determination type? Try to use ShortName attribute and create Extension for enum

2021-03-22 07:25 UTC, tatianaIljina commented on Services/AuctionApplication/AuctionApplication.API/Controllers/SupplierDeterminationTypesController.cs
> +    /// [ApiController]
is it necessary?

2021-03-22 08:16 UTC, Anny777 requested changes

2021-03-22 08:16 UTC, Anny777 commented on Services/AuctionApplication/AuctionApplication.API/Controllers/SupplierDeterminationTypesController.cs
> +            catch (ArgumentException ex)
Delete try/catch. Return Bad request, where user enters incorrect data. It is also unlikely that this exception will be thrown. Just this.Ok(typeof(SupplierDeterminationType).GetKeyShortValuePairs());

2021-03-22 08:45 UTC, Anny777 approved these changes

2021-03-22 08:55 UTC, merged