Feature/smr api
ssds-team/Tenders pull request #863
Opened 2021-04-09 11:13 UTC by kpatrashanu

2021-04-09 12:43 UTC, Anny777 requested changes

2021-04-09 12:43 UTC, Anny777 commented on Services/Smr/Smr.API/Abstraction/Models/IInfoSmr.cs
> +        public string ExternalId { get; set; }
Rename on NotificationNumber

2021-04-09 12:43 UTC, Anny777 commented on Services/Smr/Smr.API/Controllers/InfoSmrController.cs
> +                    return this.CreatedAtAction(string.Empty, createdObjectIds);
Get(Guid id) without string.Empty.

2021-04-09 12:43 UTC, Anny777 commented on Services/Smr/Smr.API/Controllers/InfoSmrController.cs
> +                return this.Conflict("The object exist");
Not good idea. Need to discuss

2021-04-09 12:43 UTC, Anny777 commented on Services/Smr/Smr.API/Migrations/20210408153736__InitialCreate.cs
> +            migrationBuilder.CreateTable(
All properties must be not nullable.

2021-04-09 12:43 UTC, Anny777 commented on Services/Smr/Smr.API/Services/InfoSmrRepository.cs
> +        public async Task<InfoSmr> GetAsync(Guid id)
Rename FindAsync

2021-04-09 12:43 UTC, Anny777 commented on Services/Smr/Smr.API/Services/InfoSmrRepository.cs
> +        private static void Validate(IEnumerable<InfoSmrDto> infoSmrDto)
infoSmrDtos instead infoSmrDto

2021-04-09 12:43 UTC, Anny777 commented on Services/Smr/Smr.API/Services/InfoSmrRepository.cs
> +                var isExist = await this.FindAsync(infoSmrDto.ExternalId).ConfigureAwait(false);
Maybe subtract existing ones with one request, out of loop.

2021-04-12 09:55 UTC, DamienVStone commented on Services/Smr/Smr.API/Abstraction/Models/IInfoSmr.cs
> +        public string Url { get; set; }
Name should be Uri as well

2021-04-13 13:41 UTC, Anny777 requested changes

2021-04-13 13:41 UTC, Anny777 commented on Services/Smr/Smr.API/Abstraction/Models/IInfoSmr.cs
> +        public DateTime StartDate { get; set; }
Deleted unused property

2021-04-13 13:41 UTC, Anny777 commented on Services/Smr/Smr.API/Abstraction/Models/IInfoSmr.cs
> +        public Guid Id { get; set; }
Added DateTime CreatedDate property

2021-04-14 06:50 UTC, Anny777 approved these changes

2021-04-14 06:51 UTC, merged