Refactored Eiszhs Monitoring service
ssds-team/Tenders pull request #908
Opened 2021-05-17 15:30 UTC by Chainsaw-does-brr

1. Cleaned (hopefully) and regrouped logic into semantic steps:
- Get latest non-cached sites
- Get potential recipients
- Try and save sites into API
- Enqueue notifications for each of the site.

2. Tried to separate the domain layer.
3. Removed a lot of breaking the flow exceptions.
4. Removed a lot of unnecessary logging and moved it to validation behavior.
5. Wrote some tests.
6. Added SuggestedInsurancePremium for upcoming feature.
7. Disabled couple of code smell rules on the projects. 

Things to pay extra attention to:
- Program.cs
- Tests.
- Minimum required ammount of data to constitute a meaningful notification (atm - siteId, developerId and inn).
- try catch blocks

ps: never launched the bloody thing, so there's one possible issue :>

2021-05-18 08:06 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesHandler.cs
> +        }
Maybe this should be paralleled via Task.WhenAll?

2021-05-24 08:50 UTC, DamienVStone requested changes
It's look like static analyzer disabled

2021-05-24 08:50 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Client/InfoEiszhsClient.cs
> +            var content = infoResidentialConstructionDto.ToJsonStringContent();
Why you removed using?

2021-05-24 08:50 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/EnqueueMailNotification/EnqueueMailNotificationResult.cs
> +            return new EnqueueMailNotificationResult(houseId: houseId, message: message, isSuccess: true);
You can escape of using named parameters, just pass them with correct sequence

2021-05-24 08:50 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesCommandValidator.cs
> +            this.RuleFor(x => x).NotNull().WithSeverity(Severity.Error);
Are you sure that you need separated validator for 1 property? Just add null check to ctor of command

2021-05-24 08:50 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesHandler.cs
> +            this.proxiedHttpClient = proxiedHttpClient;
add null checks to service injections

2021-05-24 08:50 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesHandler.cs
> +                    this.logger.LogError($"{MethodBase.GetCurrentMethod()} current retry attempt", retryAttempt);
why you using reflection if you already know current method?

2021-05-24 08:50 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesResult.cs
> +            this.Sites = sites;
Is sites null allowed?

2021-05-24 08:50 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesResultValidator.cs
> +            this.RuleFor(x => x.Sites).NotEmpty().WithSeverity(Severity.Error);
look to GetEizshsConstructionSitesCommandValidator comment

2021-05-24 08:53 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/EnqueueMailNotification/EnqueueMailNotificationResult.cs
> +            return new EnqueueMailNotificationResult(houseId: houseId, message: message, isSuccess: true);
That's exactly the point - if i change the sequence - all the code will break because multiple parameters have the same type. This is a safeguard mechanism.

2021-05-24 08:55 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Client/InfoEiszhsClient.cs
> +            var content = infoResidentialConstructionDto.ToJsonStringContent();
StringContent does not implement an IDisposable interface.

2021-05-24 08:56 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesCommandValidator.cs
> +            this.RuleFor(x => x).NotNull().WithSeverity(Severity.Error);
Validators have a generic validation behavior with built-in logging. This way i don't have to manually log validation fails.

2021-05-24 09:05 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesResult.cs
> +            this.Sites = sites;
That is controlled by validator.

2021-05-24 09:06 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesHandler.cs
> +                    this.logger.LogError($"{MethodBase.GetCurrentMethod()} current retry attempt", retryAttempt);
Didn't touch this bit of code. Replaced with ClassName.MethodName

2021-05-24 09:06 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesHandler.cs
> +            this.proxiedHttpClient = proxiedHttpClient;
Done

2021-05-24 09:08 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesResultValidator.cs
> +            this.RuleFor(x => x.Sites).NotEmpty().WithSeverity(Severity.Error);
Same as before. Allows to remove the validation logic from readers and generalize it with validation behavior.

2021-05-24 09:20 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesCommandValidator.cs
> +            this.RuleFor(x => x).NotNull().WithSeverity(Severity.Error);
Ah, generic behavior... But you allows to create command with invalid state, Is your application working good without part of required configs?)

2021-05-24 09:29 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesCommandValidator.cs
> +            this.RuleFor(x => x).NotNull().WithSeverity(Severity.Error);
Part of required configs?
Idea is that you don't need to try{} to create a command, you just do. And then you try to execute a behavior with what you have and the behavior itself knows if it can work with what you got or not. I believe, that's the point of a mediator, no? :>

2021-05-24 09:59 UTC, DamienVStone requested changes

2021-05-24 09:59 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesHandler.cs
> +                    this.logger.LogError(ex.ToString());
Pass exception to parameter instead of use .ToString method

2021-05-24 09:59 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/ReadConstructionSitePage/ReadConstructionSitePageCommandValidator.cs
> +            this.RuleFor(x => x.HoudeId).NotEmpty().WithSeverity(Severity.Error);
x.Hou**d**eId?

2021-05-24 10:50 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/ReadConstructionSitePage/ReadConstructionSitePageCommandValidator.cs
> +            this.RuleFor(x => x.HoudeId).NotEmpty().WithSeverity(Severity.Error);
Fixed

2021-05-24 10:50 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Commands/GetEizshsConstructionSites/GetEizshsConstructionSitesHandler.cs
> +                    this.logger.LogError(ex.ToString());
Fixed

2021-05-24 11:56 UTC, DamienVStone requested changes

2021-05-24 11:56 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Domain/EiszhsConstants.cs
> +        public const string EmptyNumberPattern = "^0+$";
I found that it used in only one place...

2021-05-24 11:56 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Eiszhs.Monitoring.csproj
> -		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
Mmmmmmm it's not a solution

2021-05-24 11:56 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Minor Code Smell", "S3717:Track use of \"NotImplementedException\"", Justification = "Web proxy logic is not implemented.", Scope = "module")]
Use NotSupportedException instead.

2021-05-24 11:56 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/Models/EiszhsOptions.cs
> -        public Uri GetHousePageUriTemplate(string houseId)
Is it not using anymore?

2021-05-24 11:56 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.Monitoring/stylecop.json
> +  // ACTION REQUIRED: This file was automatically added to your project, but it
Does you create it accidentally?

2021-05-24 11:56 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.UnitTests/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Style", "IDE0039:Use local function", Justification = "Local functions create clutter and take 5 times the space.", Scope = "module")]
let's talk about it

2021-05-24 12:05 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/stylecop.json
> +  // ACTION REQUIRED: This file was automatically added to your project, but it
Yea, i did. That button is 1st when you try to generate a file header and you often click it on autopilot. Will remove.

2021-05-24 12:06 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Models/EiszhsOptions.cs
> -        public Uri GetHousePageUriTemplate(string houseId)
It had no references in the 1st place.

2021-05-24 12:07 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Domain/EiszhsConstants.cs
> +        public const string EmptyNumberPattern = "^0+$";
It's purely to abstain from using magic numbers. Or strings in this case.

2021-05-24 12:27 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Eiszhs.Monitoring.csproj
> -		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
That was back at the start when i tried to suppress countless errors on even the simplest of change, before i got the hang of suppression.
+ it didn't work for some reason. *shrug*

2021-05-24 12:29 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Eiszhs.Monitoring.csproj
> -		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
Returned to how it was.

2021-05-24 12:29 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Minor Code Smell", "S3717:Track use of \"NotImplementedException\"", Justification = "Web proxy logic is not implemented.", Scope = "module")]
Done.

2021-05-24 12:30 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.UnitTests/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Style", "IDE0039:Use local function", Justification = "Local functions create clutter and take 5 times the space.", Scope = "module")]
https://www.youtube.com/watch?v=0oFYPNt57x0

2021-05-24 12:31 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/stylecop.json
> +  // ACTION REQUIRED: This file was automatically added to your project, but it
Removed

2021-05-24 12:42 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Models/EiszhsOptions.cs
> -        public Uri GetHousePageUriTemplate(string houseId)
Actually scratch that, i moved this method to handler

2021-05-24 12:43 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.Monitoring/Models/EiszhsOptions.cs
> -        public Uri GetHousePageUriTemplate(string houseId)
Same with other methods

2021-06-01 07:10 UTC, DamienVStone approved these changes

2021-06-01 07:24 UTC, Anny777 approved these changes

2021-06-01 07:37 UTC, merged