Feature/add suggested insurance premium
ssds-team/Tenders pull request #912
Opened 2021-05-20 15:52 UTC by Chainsaw-does-brr

Changed repository to work with proper internal representation instead of external dtos.
Added fields to data object to represent premiums.
Added Cancellation Tokens

2021-05-21 12:45 UTC, DamienVStone commented on Services/Eiszhs/Eiszhs.API/GlobalSuppressions.cs
> +[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Excessive documentation is harmful.", Scope = "module")]
Nice try)

2021-05-21 13:00 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/GlobalSuppressions.cs
> +[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Excessive documentation is harmful.", Scope = "module")]
Ehehe. Well, i honestly tried writing the comments, but all of them were "Gets or sets {propertyName}" which is an absurd waste of time and space :>

2021-05-24 12:48 UTC, Anny777 requested changes

2021-05-24 12:48 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Controllers/InfozhsController.cs
> +                this.logger.LogError(ex, "UniqueIndexViolationException!");
Leave LogWarning

2021-05-24 12:48 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Dtos/Extensions/InfoResidentialConstructionDtoExtensions.cs
> +        public static InfoResidentialConstruction MapFromDto(this InfoResidentialConstructionDto dto)
Maybe use automapper?

2021-05-24 12:48 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +                return filteredSites.Select(c => c.HouseId);
Materialize

2021-05-24 12:48 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +            return await this.db.InfoResidentialConstructions.FindAsync(new[] { (object)id }, cancellationToken: ct).ConfigureAwait(false);
Why new[] { (object)id }? Why not just id?

2021-05-24 12:48 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +            var filteredList = new List<InfoResidentialConstruction>(infoResidentialConstructions.Count());
Why are you doing this: infoResidentialConstructions.Count()

2021-05-24 12:48 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Persistence/Migrations/20201223085651__1.Designer.cs
> +namespace Eiszhs.API.Persistence.Migrations
Why folder rename?

2021-05-24 13:02 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/Dtos/Extensions/InfoResidentialConstructionDtoExtensions.cs
> +        public static InfoResidentialConstruction MapFromDto(this InfoResidentialConstructionDto dto)
I mean, there's only one mapping action in the whole api. Easier to do it manually.

2021-05-24 13:04 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/Controllers/InfozhsController.cs
> +                this.logger.LogError(ex, "UniqueIndexViolationException!");
Why warning though? It's clearly an error.
Supposedly - this action can never occur under normal circumstances, because CreateAsync filters out already existing objects.

2021-05-24 13:04 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +                return filteredSites.Select(c => c.HouseId);
Huh? Explain like i'm 5 :>

2021-05-24 13:05 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +            return await this.db.InfoResidentialConstructions.FindAsync(new[] { (object)id }, cancellationToken: ct).ConfigureAwait(false);
The compiler fails to bind method properly because one of the overloads has params as a 1st parameter. It's a known limitation.
https://github.com/dotnet/efcore/issues/12012#issuecomment-389274004

2021-05-24 13:09 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Controllers/InfozhsController.cs
> +                this.logger.LogError(ex, "UniqueIndexViolationException!");
Yes really, did not look into repository, then it can completely remove the catch

2021-05-24 13:10 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +            var filteredList = new List<InfoResidentialConstruction>(infoResidentialConstructions.Count());
To prevent additional memory allocation during increase of list capacity.

2021-05-24 13:10 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +                return filteredSites.Select(c => c.HouseId);
ToList() or ToArray() for example

2021-05-24 13:11 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +            return await this.db.InfoResidentialConstructions.FindAsync(new[] { (object)id }, cancellationToken: ct).ConfigureAwait(false);
How then did it work?

2021-05-24 13:14 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/Persistence/Migrations/20201223085651__1.Designer.cs
> +namespace Eiszhs.API.Persistence.Migrations
I just found it a bit hard to read the project with classes being all over the place, so made a little reshuffle. This particular was to aggregate all efcore configuration in a common folder (contains migrations and DbContext).

2021-05-24 13:15 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/Controllers/InfozhsController.cs
> +                this.logger.LogError(ex, "UniqueIndexViolationException!");
There is a case, if multiple apis will write at the same time - then this exception might occur.

2021-05-24 13:16 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/Controllers/InfozhsController.cs
> +                this.logger.LogError(ex, "UniqueIndexViolationException!");
I mean, not sure how probable it is, can remove it if you want.

2021-05-24 13:16 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +                return filteredSites.Select(c => c.HouseId);
Is there a reason for it? Method returns IEnumerable.

2021-05-24 13:18 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +            return await this.db.InfoResidentialConstructions.FindAsync(new[] { (object)id }, cancellationToken: ct).ConfigureAwait(false);
Because there was no Cancellation token. This binded method to overload with one parameter and all was dandy. But when i try to supply 2 parameters, compiler tries to bind both of them to "params" argument, instead of binding id to params and token to token.

2021-05-24 13:34 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Dtos/Extensions/InfoResidentialConstructionDtoExtensions.cs
> +        public static InfoResidentialConstruction MapFromDto(this InfoResidentialConstructionDto dto)
Ok

2021-05-24 14:05 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +            var filteredList = new List<InfoResidentialConstruction>(infoResidentialConstructions.Count());
Usually used for optimizations, but okay.

2021-05-24 14:07 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Controllers/InfozhsController.cs
> +                this.logger.LogError(ex, "UniqueIndexViolationException!");
If multiple apis will write at the same time, then you need to leave the previous implementation.

2021-05-24 14:44 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/Controllers/InfozhsController.cs
> +                this.logger.LogError(ex, "UniqueIndexViolationException!");
Fair enough. But wouldn't that cause both apis to retry at the same time and both fail again? Not sure how efcore resolves this.

2021-05-24 15:00 UTC, Chainsaw-does-brr commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +                return filteredSites.Select(c => c.HouseId);
So far, it appears that materialization is somehow connected to efcore queries? I assume, IEnumerable by itself only describes a call and to make it you need to try reading something from it either by iterating though collection or converting it?

2021-05-24 15:25 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +                return filteredSites.Select(c => c.HouseId);
As far as i know select will be called for each item in the collection, thus consuming resources, while materialization helps to avoid it. https://www.jetbrains.com/help/resharper/PossibleMultipleEnumeration.html
But in your case, you can probably leave it, since the selection is just happening, I looked at the rest of the code.

2021-05-24 15:26 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Services/InfoResidentialConstructionRepository.cs
> +            return await this.db.InfoResidentialConstructions.FindAsync(new[] { (object)id }, cancellationToken: ct).ConfigureAwait(false);
ok

2021-05-24 15:27 UTC, Anny777 commented on Services/Eiszhs/Eiszhs.API/Persistence/Migrations/20201223085651__1.Designer.cs
> +namespace Eiszhs.API.Persistence.Migrations
ok

2021-06-01 07:12 UTC, DamienVStone approved these changes

2021-06-01 07:23 UTC, Anny777 approved these changes

2021-06-01 07:24 UTC, merged